### PR TITLE
chore: add video on using kind

### PR DESCRIPTION
**Pull request by cdrage**
Adds a short video using kind

Reference: containers/podman-desktop-internal#349

### CODE REVIEW

**Review by axel7083 — COMMENTED** [review]
should we use a different naming ? `video/guide.mp4` seems a bit too generic ?

**Comment by cdrage** [comment]
Updated @axel7083

**Comment by axel7083** [comment]
I will be a bit annoying, but cluster-creation could conflict if we decide to add a cluster-creation-minikube :)

**Review by benoitf — COMMENTED** [review]
cluster-creation-kind.mp4

**Comment by cdrage** [comment]
`cluster-creation-kind.mp4` it is! changed the name

**Pull request merged**
